#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jcommander
Version  : 1.12
Release  : 2
URL      : https://github.com/cbeust/jcommander/archive/jcommander-1.12.tar.gz
Source0  : https://github.com/cbeust/jcommander/archive/jcommander-1.12.tar.gz
Source1  : https://repo1.maven.org/maven2/com/beust/jcommander/1.12/jcommander-1.12.jar
Source2  : https://repo1.maven.org/maven2/com/beust/jcommander/1.12/jcommander-1.12.pom
Source3  : https://repo1.maven.org/maven2/com/beust/jcommander/1.35/jcommander-1.35.jar
Source4  : https://repo1.maven.org/maven2/com/beust/jcommander/1.35/jcommander-1.35.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jcommander-data = %{version}-%{release}
Requires: mvn-jcommander-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
JCommander
==========
This is an annotation based parameter parsing framework for Java.

%package data
Summary: data components for the mvn-jcommander package.
Group: Data

%description data
data components for the mvn-jcommander package.


%package license
Summary: license components for the mvn-jcommander package.
Group: Default

%description license
license components for the mvn-jcommander package.


%prep
%setup -q -n jcommander-jcommander-1.12

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-jcommander
cp license.txt %{buildroot}/usr/share/package-licenses/mvn-jcommander/license.txt
cp src/main/license/license-header.txt %{buildroot}/usr/share/package-licenses/mvn-jcommander/src_main_license_license-header.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.12/jcommander-1.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.12/jcommander-1.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.35
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.35
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/beust/jcommander/1.12/jcommander-1.12.jar
/usr/share/java/.m2/repository/com/beust/jcommander/1.12/jcommander-1.12.pom
/usr/share/java/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.jar
/usr/share/java/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-jcommander/license.txt
/usr/share/package-licenses/mvn-jcommander/src_main_license_license-header.txt
